---
user:
  id: 2712105793
  idstr: '2712105793'
  screen_name: 2012喽奋斗
  name: 2012喽奋斗
  province: '31'
  city: '1000'
  location: 上海
  description: ''
  url: ''
  profile_image_url: http://tp2.sinaimg.cn/2712105793/50/39997304031/1
  profile_url: jaylijunjie
  domain: jaylijunjie
  weihao: ''
  gender: m
  followers_count: 3
  friends_count: 34
  statuses_count: 109
  favourites_count: 1
  created_at: Wed Apr 18 18:57:28 +0800 2012
  following: false
  allow_all_act_msg: false
  geo_enabled: true
  verified: false
  verified_type: -1
  remark: ''
  status:
    created_at: Sat Aug 25 02:02:56 +0800 2012
    id: 3482731575302326
    mid: '3482731575302326'
    idstr: '3482731575302326'
    text: upload img from local
    source: <a href="" rel="nofollow">未通过审核应用</a>
    favorited: false
    truncated: false
    in_reply_to_status_id: ''
    in_reply_to_user_id: ''
    in_reply_to_screen_name: ''
    thumbnail_pic: http://ww3.sinaimg.cn/thumbnail/a1a77341jw1dw8bb38iypj.jpg
    bmiddle_pic: http://ww3.sinaimg.cn/bmiddle/a1a77341jw1dw8bb38iypj.jpg
    original_pic: http://ww3.sinaimg.cn/large/a1a77341jw1dw8bb38iypj.jpg
    geo: 
    reposts_count: 0
    comments_count: 0
    mlevel: 0
    visible:
      type: 0
      list_id: 0
  allow_all_comment: true
  avatar_large: http://tp2.sinaimg.cn/2712105793/180/39997304031/1
  verified_reason: ''
  follow_me: false
  online_status: 0
  bi_followers_count: 0
  lang: zh-cn
